/*
 * generated by Xtext 2.17.0
 */
package org.icyphy.tests

// Comment these out because they don't work in a standalone maven
// import com.google.inject.Inject
// import org.eclipse.xtext.testing.InjectWith
// import org.eclipse.xtext.testing.XtextRunner
// import org.eclipse.xtext.testing.extensions.InjectionExtension
// import org.eclipse.xtext.testing.util.ParseHelper
// import org.icyphy.linguaFranca.Model
// import org.junit.Assert
// import org.junit.Test
// import org.junit.jupiter.api.Assertions
// import org.junit.jupiter.api.^extension.ExtendWith
// import org.junit.runner.RunWith

// Here are the imports from ./src/test/java/my/hero/SuperManTest.xtend
import org.junit.Test
import static org.junit.Assert.*
// import my.pack.Foo

// Comment these out because they don't work in a standalone maven
// @RunWith(XtextRunner)
// @ExtendWith(InjectionExtension)
// @InjectWith(LinguaFrancaInjectorProvider)
class LinguaFrancaParsingTest {

        // Comment these out because they don't work in a standalone maven
	// @Inject
	// ParseHelper<Model> parseHelper

	@Test
	def void checkForTarget() {
		// val result = parseHelper.parse('''
		//	targett C;
		//	reactor Foo {
		//	}
		// ''')
		// Assert.assertNotNull(result)
		// val errors = result.eResource.errors
		// Assertions.assertFalse(errors.isEmpty, "Failed to catch misspelled target keyword.")
                print("*** Running test in src/test/java/org/icyphy/tests/LinguaFrancaParsingTest.xtend *** ")

                assertEquals(1,1);
	}
}
